# Generated by Django 3.1.1 on 2021-09-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoolerCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoDuro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuentePoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMadre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('desc0', models.CharField(default='', max_length=50)),
                ('desc1', models.CharField(default='', max_length=50)),
                ('desc2', models.CharField(default='', max_length=50)),
                ('desc3', models.CharField(default='', max_length=50)),
                ('desc4', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creación', models.DateField(default='2021-09-24')),
                ('cooler', models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.coolercpu')),
                ('discohdd', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.discoduro')),
                ('discossd', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.ssd')),
                ('fuente', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.fuentepoder')),
                ('gabinete', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.gabinete')),
                ('memoria', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.ram')),
                ('placamadre', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.placamadre')),
                ('procesador', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Componentes.procesador')),
                ('tarjetavideo', models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.gpu')),
            ],
        ),
    ]
