# Generated by Django 3.1.1 on 2021-09-22 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creación', models.DateField(default='2021-09-22')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.procesador')),
            ],
        ),
    ]
