# Generated by Django 3.1.1 on 2021-09-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Componentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.coolercpu'),
        ),
        migrations.AddField(
            model_name='build',
            name='discohdd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.discoduro'),
        ),
        migrations.AddField(
            model_name='build',
            name='discossd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.ssd'),
        ),
        migrations.AddField(
            model_name='build',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.fuentepoder'),
        ),
        migrations.AddField(
            model_name='build',
            name='gabinete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.gabinete'),
        ),
        migrations.AddField(
            model_name='build',
            name='memoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.ram'),
        ),
        migrations.AddField(
            model_name='build',
            name='placamadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.placamadre'),
        ),
        migrations.AddField(
            model_name='build',
            name='procesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componentes.procesador'),
        ),
        migrations.AddField(
            model_name='build',
            name='tarjetavideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.gpu'),
        ),
        migrations.AddField(
            model_name='build',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
