# Generated by Django 3.1.1 on 2021-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0002_auto_20210924_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='creacion',
            field=models.DateField(default='2021-09-28'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='creacion',
            field=models.DateField(default='2021-09-28'),
        ),
    ]
