# Generated by Django 3.1.1 on 2021-09-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Componentes', '0003_auto_20210922_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FuentePoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscoDuro',
        ),
        migrations.DeleteModel(
            name='FuenteDePoder',
        ),
        migrations.DeleteModel(
            name='TarjetaDeVideo',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='cooler',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='frecuencia_turbo',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='graficos',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='nucleo',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='procesador',
            name='tdp',
        ),
        migrations.AddField(
            model_name='build',
            name='cooler',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.coolercpu'),
        ),
        migrations.AddField(
            model_name='build',
            name='gabinete',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Componentes.gabinete'),
        ),
        migrations.AddField(
            model_name='build',
            name='memoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Componentes.ram'),
        ),
        migrations.AddField(
            model_name='build',
            name='placamadre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Componentes.placamadre'),
        ),
        migrations.AlterField(
            model_name='build',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='build',
            name='procesador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Componentes.procesador'),
        ),
        migrations.AlterField(
            model_name='coolercpu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gabinete',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placamadre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procesador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='build',
            name='disco',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Componentes.disco'),
        ),
        migrations.AddField(
            model_name='build',
            name='fuente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Componentes.fuentepoder'),
        ),
        migrations.AddField(
            model_name='build',
            name='tarjetavideo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Componentes.tarjetavideo'),
        ),
    ]
